feat: 팝업창 기능개선
untoc-camp/comboong-note pull request #13
Opened 2024-04-05 13:18 UTC by Squater0219

## 관련 이슈

- close #12 

## 작업 내용

- 팝업창에 학사일정,학과종지,설정 탭을 추가하고 css디자인을 추가합니다

## preview
![0DBC49E6-E564-4768-9702-3BDFF07E3172](https://github.com/untoc-camp/comboong-note/assets/141287114/423cc0a0-60b5-411f-8b17-05f9cf295cb5)

2024-04-05 13:31 UTC, hdh4952 approved these changes
좋습니다~ 코멘트 확인하고 반영하고 싶으시면 반영 후에 머지해도 될듯합니다!

2024-04-05 13:31 UTC, hdh4952 commented on assets/popup.js
> +
이 부분은 함수 하나 만들어서 넣으면 깔끔할 것 같아요

2024-04-05 13:31 UTC, hdh4952 commented on assets/popup.js
> +const COLORS = ['#024d97', '#0275ce', '#02BA6E'];
js로 색을 직접적으로 변경하는 것도 가능하지만, 저는 해당 색을 가지는 class를 만들어서 css 파일에 추가하고 해당 class를 부여하는 식으로 짜는 걸 선호합니다. 왜냐면 나중에 색을 바꾸고 싶을 때 쉽게 바꿀 수 있거든요. 이 코드처럼 상수로 놓고 바꾸는 것도 똑같다고 할 수 있지만 디자인에 관련된 건 css에 위임하고 싶은 욕심입니다. ㅎㅎ

2024-04-06 03:28 UTC, jimini1026 approved these changes
Lgtm

2024-04-07 04:51 UTC, Squater0219 commented on assets/popup.js
> +
확인했습니다~ 반영 해볼게용

2024-04-09 08:15 UTC, jimini1026 approved these changes
진짜 잘하신거 같슴다 👍

2024-04-09 14:03 UTC, hdh4952 requested changes
vscode 확장 프로그램 설치가 제대로 안된 것 같습니다.  확인 부탁드려요. (prettier, eslint)

팝업창 디자인 아주 좋습니다.

전체적인 구조가 덜 잡힌 것 같은데 나중에 리팩토링하면서 진행합시다!

2024-04-11 07:50 UTC, hdh4952 approved these changes
👍

2024-04-11 07:51 UTC, merged