refactor: 스토리지 리팩터링
untoc-camp/comboong-note pull request #26
Opened 2024-05-09 08:05 UTC by Squater0219

## 관련 이슈

- close #25 
## 작업 내용

- popup.js에 storage.js에서 export한 localStorageGet모듈을 추가합니다

## preview

2024-05-13 01:28 UTC, jimini1026 requested changes
스크립트 태그는 body 마지막에 넣어주는게 좋을거 같애요
위에 넣으면 렌더링에 방해가 될 수도 있습니다!

2024-05-13 01:28 UTC, jimini1026 commented on scripts/storage.js
> +  return new Promise((resolve) => {
ㅇ0ㅇ 코드 어캐 짜야할 지 몰랐었는데 대단하시구만요

2024-05-13 01:28 UTC, jimini1026 commented on assets/popup/popup.html
> +    <script type="module" src="popup.js"></script>
혹시 스크립트 위쪽으로 올리신 이유 있나요?

2024-05-13 04:31 UTC, Squater0219 commented on assets/popup/popup.html
> +    <script type="module" src="popup.js"></script>
그 export 안되는거 해결법중에 head에 script태그 넣으면 해결된다는 글이 있어서 시도해본건데 효과 없었습니다. 다시 원복 해놓을게용

2024-05-14 03:48 UTC, jimini1026 approved these changes

2024-05-14 11:36 UTC, merged