feat: 팝업창에 크롤링 데이터 출력
untoc-camp/comboong-note pull request #9
Opened 2024-03-30 14:57 UTC by Squater0219

## 관련 이슈

- close #8 

## 작업 내용

- 학과 공지와 학사일정을 팝업창에 띄웁니다. 디자인 X

## preview
<img width="1440" alt="스크린샷 2024-03-30 오후 11 56 33" src="https://github.com/untoc-camp/comboong-note/assets/141287114/e0ee2088-9481-4abd-8a10-b0eb88444b4e">

2024-03-30 15:37 UTC, hdh4952 requested changes
코멘트 확인 부탁합니다~! 
전혀 새로운 부분이라서 고민한 부분도 있을텐데 전체적으로 잘 작성된 것 같습니다.

2024-03-30 15:37 UTC, hdh4952 commented on assets/popup.html
> +  </style>
지금은 간단한 css지만 나중을 대비해서 css파일로 만들어서 분리시키는 게 좋아보입니다~!

2024-03-30 15:37 UTC, hdh4952 commented on assets/popup.js
> +});
콜백 함수로 작성됐는데, 가독성을 위해 async/await을 이용해서 아래 코드처럼 바꿔보는 건 어떨까요?
```javascript
const { schedules, majorNotices } = await chrome.storage.local.get(['schedules', 'majorNotices']);
```

2024-03-30 15:37 UTC, hdh4952 commented on assets/popup.js
> +async function getSchedulesAndNotices(schedules, majorNotices) {
함수 선언에서 async 키워드는 제거해도 영향이 없을 것 같네요.
이 함수가 하는 역할이 popup.html에 학사일정과 공지를 렌더링하는 걸로 보이는데 getSchedulesAndNotices보다는 renderPopup이나 injectSchedulesAndNotices 같은 구현된 내용과 일치하는 함수명으로 수정하는 게 더 좋아보입니다!

2024-03-30 15:44 UTC, Squater0219 commented on assets/popup.js
> +async function getSchedulesAndNotices(schedules, majorNotices) {
확인했습니다~ 반영해서 다시 작업 해볼게용

2024-03-31 06:13 UTC, jimini1026 approved these changes
좋슴다

2024-04-01 13:58 UTC, hdh4952 approved these changes
좋습니다~

2024-04-01 14:19 UTC, merged